# TCL File Generated by Component Editor 24.1
# Sat May 02 21:45:12 GMT 2026
# DO NOT MODIFY


# 
# room_eq_peripheral "room_eq" v1.0
#  2026.05.02.21:45:12
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module room_eq_peripheral
# 
set_module_property DESCRIPTION ""
set_module_property NAME room_eq_peripheral
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME room_eq
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL room_eq_peripheral
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file room_eq_peripheral.sv SYSTEM_VERILOG PATH ../src/hardware/room_eq_peripheral/room_eq_peripheral.sv TOP_LEVEL_FILE
add_fileset_file phase_accumulator.sv SYSTEM_VERILOG PATH ../src/hardware/room_eq_peripheral/sweep_generator/phase_accumulator.sv
add_fileset_file sine_lookup.sv SYSTEM_VERILOG PATH ../src/hardware/room_eq_peripheral/sweep_generator/sine_lookup.sv
add_fileset_file sweep_generator.sv SYSTEM_VERILOG PATH ../src/hardware/room_eq_peripheral/sweep_generator/sweep_generator.sv
add_fileset_file i2s_clock_gen.sv SYSTEM_VERILOG PATH ../src/hardware/room_eq_peripheral/i2s_tx/i2s_clock_gen.sv
add_fileset_file i2s_shift_register.sv SYSTEM_VERILOG PATH ../src/hardware/room_eq_peripheral/i2s_tx/i2s_shift_register.sv
add_fileset_file i2s_tx.sv SYSTEM_VERILOG PATH ../src/hardware/room_eq_peripheral/i2s_tx/i2s_tx.sv
add_fileset_file sine_lut.sv SYSTEM_VERILOG PATH ../src/hardware/memory/sine_lut.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 address address Input 11
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point audio
# 
add_interface audio conduit end
set_interface_property audio associatedClock clock
set_interface_property audio associatedReset ""
set_interface_property audio ENABLED true
set_interface_property audio EXPORT_OF ""
set_interface_property audio PORT_NAME_MAP ""
set_interface_property audio CMSIS_SVD_VARIABLES ""
set_interface_property audio SVD_ADDRESS_GROUP ""

add_interface_port audio AUD_BCLK bclk Output 1
add_interface_port audio AUD_DACDAT dacdat Output 1
add_interface_port audio AUD_DACLRCK daclrck Output 1
add_interface_port audio AUD_XCK xck Output 1


# 
# connection point audio_clk
# 
add_interface audio_clk clock end
set_interface_property audio_clk clockRate 0
set_interface_property audio_clk ENABLED true
set_interface_property audio_clk EXPORT_OF ""
set_interface_property audio_clk PORT_NAME_MAP ""
set_interface_property audio_clk CMSIS_SVD_VARIABLES ""
set_interface_property audio_clk SVD_ADDRESS_GROUP ""

add_interface_port audio_clk audio_clk clk Input 1

