// ==================== MODULE INTERFACE ====================
// I2S receiver.  Deserializes the codec ADC serial data stream
// into stereo 24-bit parallel samples.
//
// Runs in the 12.288 MHz clock domain, sharing BCLK and LRCK
// generated by i2s_tx's clock_gen (the FPGA is the I2S master).
//
// The codec drives ADCDAT synchronized to BCLK: data transitions
// on BCLK falling edge, stable for sampling on BCLK rising edge.
//
// I2S format (Philips):
//   - MSB-first, 1-bit delay after LRCK transition
//   - 24 data bits + 8 don't-care padding bits per channel
//   - 64 BCLK cycles per stereo frame
//   - LRCK low = left channel, LRCK high = right channel
//
// Frame layout (bit_cnt 0-63):
//   LRCK falls → bit_cnt 0 (delay slot) → bits 1-24 (left data)
//              → bits 25-31 (padding)
//   LRCK rises → bit_cnt 32 (delay slot) → bits 33-56 (right data)
//              → bits 57-63 (padding)
//
// Inputs:
//   clock        - 12.288 MHz master clock (from PLL)
//   reset        - active-high synchronous reset
//   bclk         - 3.072 MHz bit clock (from i2s_clock_gen)
//   lrck         - 48 kHz frame clock (from i2s_clock_gen)
//   adcdat       - serial data from codec ADC (PIN_K7)
//
// Outputs:
//   left_sample  - 24-bit deserialized left channel
//   right_sample - 24-bit deserialized right channel
//   sample_valid - one-cycle pulse when a new stereo pair is ready
// ===========================================================

module i2s_rx (
    input  logic        clock,
    input  logic        reset,
    input  logic        bclk,
    input  logic        lrck,
    input  logic        adcdat,
    output logic [23:0] left_sample,
    output logic [23:0] right_sample,
    output logic        sample_valid
);

    // ── BCLK rising-edge detection ───────────────────────
    // bclk is a data signal toggled at 12.288 MHz / 4.
    // Detect 0→1 transitions by comparing current vs previous.
    logic bclk_d;
    wire  bclk_rise = bclk && !bclk_d;

    always_ff @(posedge clock) begin
        if (reset) bclk_d <= 1'b0;
        else       bclk_d <= bclk;
    end

    // ── Bit counter ──────────────────────────────────────
    // Counts 0-63 within each I2S frame.  Resets to 0 when
    // LRCK falls (start of left channel).
    logic [5:0] bit_cnt;
    logic       lrck_d;

    always_ff @(posedge clock) begin
        if (reset) begin
            bit_cnt <= 6'd0;
            lrck_d  <= 1'b0;
        end else if (bclk_rise) begin
            lrck_d <= lrck;
            if (lrck_d && !lrck)        // LRCK falling edge
                bit_cnt <= 6'd0;
            else
                bit_cnt <= bit_cnt + 6'd1;
        end
    end

    // ── Shift registers ──────────────────────────────────
    // Shift in ADCDAT on BCLK rising edges during data slots.
    //
    // Timing: the transmitter (codec or i2s_tx) drives ADCDAT at
    // BCLK falling edge. Due to the 1-bit I2S delay plus our
    // bclk_rise detection latency, the MSB driven at the LRCK
    // transition is stable on the wire at our bit_cnt=0 rising edge.
    // We capture:
    //   Left channel:  bit_cnt 0..23  (24 bits, MSB first)
    //   Right channel: bit_cnt 32..55 (24 bits, MSB first)
    logic [23:0] shift_l, shift_r;

    always_ff @(posedge clock) begin
        if (reset) begin
            shift_l <= 24'd0;
            shift_r <= 24'd0;
        end else if (bclk_rise) begin
            if (bit_cnt <= 6'd23)
                shift_l <= {shift_l[22:0], adcdat};
            if (bit_cnt >= 6'd32 && bit_cnt <= 6'd55)
                shift_r <= {shift_r[22:0], adcdat};
        end
    end

    // ── Output latch ─────────────────────────────────────
    // Latch complete samples after right channel LSB is captured.
    // bit_cnt == 56 is the first padding BCLK after right data.
    // Pulse sample_valid for one 12.288 MHz clock cycle.
    always_ff @(posedge clock) begin
        if (reset) begin
            left_sample  <= 24'd0;
            right_sample <= 24'd0;
            sample_valid <= 1'b0;
        end else begin
            sample_valid <= 1'b0;
            if (bclk_rise && bit_cnt == 6'd56) begin
                left_sample  <= shift_l;
                right_sample <= shift_r;
                sample_valid <= 1'b1;
            end
        end
    end

endmodule
