`timescale 1ns / 1ps
// ── tb_calibration_engine.sv ──────────────────────────────────────────────────
// Integration testbench for calibration_engine.sv.
//
// IVerilog (make sim_calibration_engine):
//   Uses capture_fft_sim.v echo stub.  The stub buffers one 8192-sample frame
//   and echoes it back unchanged (no math), so rd_real[i] == input[i] and
//   rd_imag[i] == 0.  Tests T1-T6.
//
// Questa (make sim_calibration_engine_fft, compiled with +define+QUESTA_FFT):
//   Uses the real Altera FFT II VHDL IP.  Additionally runs T7, which loads
//   golden FFT output from sim_out/ (generated by gen_golden_fft.py) and
//   compares every bin within +/-16 LSB to account for R22SDF fixed-point error.
// ─────────────────────────────────────────────────────────────────────────────

module tb_calibration_engine;

    // ── Clock periods ─────────────────────────────────────────
    localparam SYSCLK_PERIOD = 20;  // 50 MHz
    localparam BCLK_PERIOD   = 100; // 10 MHz (real: 3.072 MHz; sped up for sim)
    // Gray-code CDC from bclk write side to sysclk read side:
    // 1 bclk (100 ns) + rdsync_delaypipe=4 sysclk (80 ns) = 180 ns.
    // 20 sysclk = 400 ns — comfortable margin.
    localparam CDC_WAIT      = 20;

    // ── DUT ports ─────────────────────────────────────────────
    logic        sysclk;
    logic        bclk;
    logic        lrclk;
    // aclr is driven via continuous assign because dcfifo in altera_mf.v
    // declares its aclr port as tri0 unconditionally, which IVerilog propagates
    // up the hierarchy and blocks procedural assignment to a plain logic.
    reg          aclr_drv;
    wire         aclr;
    assign aclr = aclr_drv;
    logic [23:0] left_chan;
    logic [12:0] rd_addr;
    logic [23:0] rd_real;
    logic [23:0] rd_imag;
    logic        fft_done;
    logic        start;

    // ── DUT ───────────────────────────────────────────────────
    calibration_engine dut (
        .sysclk   (sysclk),
        .bclk     (bclk),
        .lrclk    (lrclk),
        .aclr     (aclr),
        .start    (start),
        .left_chan (left_chan),
        .rd_addr  (rd_addr),
        .rd_real  (rd_real),
        .rd_imag  (rd_imag),
        .fft_done (fft_done)
    );

    // ── Clocks ────────────────────────────────────────────────
    initial sysclk = 0;
    always #(SYSCLK_PERIOD / 2) sysclk = ~sysclk;
    initial bclk   = 0;
    always #(BCLK_PERIOD   / 2) bclk   = ~bclk;

    // ── send_sample ───────────────────────────────────────────
    // Injects one 24-bit audio sample via the I2S interface.
    // sample_fifo detects lrclk's falling edge on bclk posedge and
    // writes left_chan to the DCFIFO on the following bclk posedge.
    task automatic send_sample(input [23:0] sample);
        left_chan = sample;
        @(posedge bclk); #1;
        lrclk = 0;           // falling edge: sample_fifo captures left_chan
        @(posedge bclk); #1; // FIFO write happens on this bclk posedge
        lrclk = 1;
    endtask

    // ── read_result ───────────────────────────────────────────
    // Reads one complex bin from fft_result_ram (1-cycle latency).
    task automatic read_result(
        input  [12:0] addr,
        output [23:0] rr,
        output [23:0] ri
    );
        @(posedge sysclk); #1;
        rd_addr = addr;
        @(posedge sysclk); #1;
        rr = rd_real;
        ri = rd_imag;
    endtask

    // ── check ─────────────────────────────────────────────────
    task automatic check(
        input [23:0] got,
        input [23:0] expected,
        input string label
    );
        if (got !== expected)
            $display("FAIL [%s]  got=0x%06h  expected=0x%06h", label, got, expected);
        else
            $display("PASS [%s]  got=0x%06h", label, got);
    endtask

    // ── Questa-only: golden FFT arrays ────────────────────────
    // Signal: cosine at bin 64, integer amplitude 512, 8192 samples.
    // Generated by gen_golden_fft.py — must be run before the Questa target.
`ifdef QUESTA_FFT
    logic [23:0] fft_input_data   [0:8191];
    logic [23:0] golden_real_data [0:8191];
    logic [23:0] golden_imag_data [0:8191];

    initial begin
        $readmemh("sim_out/fft_input.hex",       fft_input_data);
        $readmemh("sim_out/fft_golden_real.hex",  golden_real_data);
        $readmemh("sim_out/fft_golden_imag.hex",  golden_imag_data);
    end
`endif

    // ── Test variables ────────────────────────────────────────
    integer      i;
    integer      timeout_cnt;
    logic [23:0] rr, ri;

    // ── Test sequence ─────────────────────────────────────────
    initial begin
        aclr_drv  = 1;
        start     = 0;
        lrclk     = 1;
        left_chan  = 24'h0;
        rd_addr   = 13'd0;

        // ── T1: aclr holds fft_done=0; 2-FF synchronizer recovers ─
        repeat (4) @(posedge sysclk); #1;
        if (fft_done === 1'b0)
            $display("PASS [T1] fft_done=0 during aclr");
        else
            $display("FAIL [T1] expected fft_done=0 during aclr, got %b", fft_done);
        aclr_drv = 0;
        // 2-FF synchronizer: reset_n_ff1 goes high after cycle 1,
        // reset_n_ff2 (= reset_n) goes high after cycle 2.  Wait 4 for margin.
        repeat (4) @(posedge sysclk); #1;
        if (dut.reset_n_ff2 === 1'b1)
            $display("PASS [T1] reset_n_ff2=1 after synchronizer propagates");
        else
            $display("FAIL [T1] reset_n_ff2=%b 4 cycles after aclr released", dut.reset_n_ff2);

        // Arm the pipeline so T2 genuinely tests partial-frame behavior.
        @(posedge sysclk); #1; start = 1;
        @(posedge sysclk); #1; start = 0;

        // ── T2: fft_done stays 0 during a partial frame ───────
        // Send 32 samples (far fewer than 8192) — fft_done must not fire.
        for (i = 0; i < 32; i++)
            send_sample(24'hAB0000 | i[23:0]);
        repeat (CDC_WAIT) @(posedge sysclk); #1;
        if (fft_done === 1'b0)
            $display("PASS [T2] fft_done=0 after partial frame (32 of 8192 samples)");
        else
            $display("FAIL [T2] fft_done asserted prematurely after only 32 samples");

        // ── T3: aclr mid-operation clears fft_done ────────────
        // Complete one full frame (assert fft_done), then assert aclr and
        // verify fft_done drops immediately.
        aclr_drv = 1; repeat (4) @(posedge sysclk); #1;
        aclr_drv = 0; repeat (4) @(posedge sysclk);
        @(posedge sysclk); #1; start = 1;
        @(posedge sysclk); #1; start = 0;
        for (i = 0; i < 8192; i++)
            send_sample(24'hCC0000 | (i[23:0] & 24'h0000FF));
        timeout_cnt = 0;
        while (fft_done !== 1'b1 && timeout_cnt < 60000) begin
            @(posedge sysclk); #1;
            timeout_cnt++;
        end
        if (fft_done !== 1'b1) begin
            $display("FAIL [T3 setup] fft_done never asserted for first frame (timeout)");
        end else begin
            $display("PASS [T3 setup] fft_done=1 after first frame");
            aclr_drv = 1; repeat (4) @(posedge sysclk); #1;
            if (fft_done === 1'b0)
                $display("PASS [T3] fft_done=0 after aclr mid-operation");
            else
                $display("FAIL [T3] expected fft_done=0 after aclr, got %b", fft_done);
            aclr_drv = 0; repeat (4) @(posedge sysclk);
        end

`ifndef QUESTA_FFT
        // ── T4: Full pipeline end-to-end data integrity ────────
        // Send 8192 samples with unique per-address values, wait for fft_done,
        // then spot-check read-back.  The echo stub passes real through
        // unchanged (rd_real[i] == input[i]) and zeroes imaginary (rd_imag == 0).
        aclr_drv = 1; repeat (4) @(posedge sysclk); #1;
        aclr_drv = 0; repeat (4) @(posedge sysclk);
        @(posedge sysclk); #1; start = 1;
        @(posedge sysclk); #1; start = 0;
        for (i = 0; i < 8192; i++)
            send_sample(24'h700000 | i[23:0]);

        timeout_cnt = 0;
        while (fft_done !== 1'b1 && timeout_cnt < 60000) begin
            @(posedge sysclk); #1;
            timeout_cnt++;
        end

        if (fft_done !== 1'b1) begin
            $display("FAIL [T4] fft_done never asserted after full frame (timeout after %0d cycles)",
                     timeout_cnt);
        end else begin
            $display("PASS [T4] fft_done=1 after full 8192-sample frame");
            read_result(13'd0,    rr, ri); check(rr, 24'h700000, "T4 addr=0 real");
                                           check(ri, 24'h000000, "T4 addr=0 imag");
            read_result(13'd1,    rr, ri); check(rr, 24'h700001, "T4 addr=1 real");
                                           check(ri, 24'h000000, "T4 addr=1 imag");
            read_result(13'd255,  rr, ri); check(rr, 24'h7000FF, "T4 addr=255 real");
                                           check(ri, 24'h000000, "T4 addr=255 imag");
            read_result(13'd1024, rr, ri); check(rr, 24'h700400, "T4 addr=1024 real");
                                           check(ri, 24'h000000, "T4 addr=1024 imag");
            read_result(13'd4096, rr, ri); check(rr, 24'h701000, "T4 addr=4096 real");
                                           check(ri, 24'h000000, "T4 addr=4096 imag");
            read_result(13'd8190, rr, ri); check(rr, 24'h701FFE, "T4 addr=8190 real");
                                           check(ri, 24'h000000, "T4 addr=8190 imag");
            read_result(13'd8191, rr, ri); check(rr, 24'h701FFF, "T4 addr=8191 real");
                                           check(ri, 24'h000000, "T4 addr=8191 imag");
        end

        // ── T5: Second frame replaces first ────────────────────
        // fft_done must clear when the new frame's SOP propagates to
        // fft_result_ram, then reassert on the second EOP.
        if (fft_done === 1'b1) begin
            for (i = 0; i < 8192; i++)
                send_sample(24'hBB0000 | i[23:0]);

            // Wait for fft_done to clear (new frame SOP clears it)
            timeout_cnt = 0;
            while (fft_done !== 1'b0 && timeout_cnt < 30000) begin
                @(posedge sysclk); #1;
                timeout_cnt++;
            end
            // Then wait for fft_done to reassert on second EOP
            timeout_cnt = 0;
            while (fft_done !== 1'b1 && timeout_cnt < 60000) begin
                @(posedge sysclk); #1;
                timeout_cnt++;
            end

            if (fft_done === 1'b1) begin
                $display("PASS [T5] fft_done toggled and reasserted for second frame");
                read_result(13'd0,    rr, ri); check(rr, 24'hBB0000, "T5 frame2 addr=0 real");
                                               check(ri, 24'h000000, "T5 frame2 addr=0 imag");
                read_result(13'd8191, rr, ri); check(rr, 24'hBB1FFF, "T5 frame2 addr=8191 real");
                                               check(ri, 24'h000000, "T5 frame2 addr=8191 imag");
            end else
                $display("FAIL [T5] second frame: fft_done never reasserted (timeout)");
        end else
            $display("SKIP [T5] prerequisite T4 not met");

        // ── T6: Partial third frame does not fire fft_done ────
        // 100 samples is insufficient to complete a frame (8192 needed), so
        // fft_done must remain 1 (second-frame data still in RAM, no third-frame
        // completion) and must not re-toggle.
        if (fft_done === 1'b1) begin
            for (i = 0; i < 100; i++)
                send_sample(24'hDD0000 | i[23:0]);
            repeat (CDC_WAIT * 3) @(posedge sysclk); #1;
            if (fft_done === 1'b1)
                $display("PASS [T6] fft_done holds 1; 100-sample partial frame does not complete output");
            else
                $display("FAIL [T6] fft_done dropped unexpectedly during partial third frame");
        end else
            $display("SKIP [T6] prerequisite T5 not met");
`endif // QUESTA_FFT

`ifdef QUESTA_FFT
        // ── T7: FFT accuracy vs numpy golden data ──────────────
        // Input: x[n] = round(512 * cos(2*pi*64*n/8192)) — single cosine
        // at bin 64, amplitude 512.  With N=8192, k0=64 divides N exactly
        // (8192/64=128), so the FFT has exactly two dominant bins:
        //   X[64]  ≈ +2,097,152 (real) ≈ 0 (imag)
        //   X[8128] ≈ +2,097,152 (real) ≈ 0 (imag)   (complex conjugate)
        // All other bins are near zero.
        //
        // Tolerance: +-16 LSBs per bin.  The R22SDF architecture has 13 butterfly
        // stages; each introduces ~0.5 LSB rounding. sqrt(13)*0.5 ~ 2 LSBs worst
        // case.  +-16 gives 8x margin while still catching implementation bugs.
        begin : t7_fft_accuracy
            localparam FFT_TOL = 16;
            integer    fail_count;
            integer    bin;
            logic [23:0] act_r, act_i;
            integer dr, di;

            aclr_drv = 1; repeat (4) @(posedge sysclk); #1;
            aclr_drv = 0; repeat (4) @(posedge sysclk);
            @(posedge sysclk); #1; start = 1;
            @(posedge sysclk); #1; start = 0;

            for (i = 0; i < 8192; i++)
                send_sample(fft_input_data[i]);

            timeout_cnt = 0;
            while (fft_done !== 1'b1 && timeout_cnt < 100000) begin
                @(posedge sysclk); #1;
                timeout_cnt++;
            end

            // Golden data is scaled down by 2^14 to match the scaling changes
            // incurred by the R22SDF butterfly architecture w/ the fixed point
            // format. This should not be important for our calculations if we are 
            // normalizing anyways.
            if (fft_done !== 1'b1) begin
                $display("FAIL [T7] fft_done never asserted for accuracy frame (timeout)");
            end else begin
                fail_count = 0;
                for (bin = 0; bin < 8192; bin++) begin
                    read_result(bin[12:0], act_r, act_i);
                    dr = $signed(act_r) - $signed(golden_real_data[bin]);
                    di = $signed(act_i) - $signed(golden_imag_data[bin]);
                    if (dr < 0) dr = -dr;
                    if (di < 0) di = -di;
                    if (dr > FFT_TOL || di > FFT_TOL) begin
                        $display(
                            "FAIL [T7] bin=%4d  real: hw=%8d np=%8d |diff|=%0d  imag: hw=%8d np=%8d |diff|=%0d",
                            bin,
                            $signed(act_r),              $signed(golden_real_data[bin]), dr,
                            $signed(act_i),              $signed(golden_imag_data[bin]), di);
                        fail_count++;
                    end
                end
                if (fail_count == 0)
                    $display("PASS [T7] all 8192 FFT bins within +/-%0d LSB tolerance", FFT_TOL);
                else
                    $display("FAIL [T7] %0d / 8192 bins exceeded +/-%0d LSB tolerance",
                             fail_count, FFT_TOL);
            end
        end
`endif

        // ── T_START: start gate blocks FFT until start is asserted ──
        // Part A: send a full frame WITHOUT pulsing start — fft_done must stay 0.
        // Part B: pulse start, send a fresh frame — fft_done must assert.
        begin
            aclr_drv = 1; repeat (4) @(posedge sysclk); #1;
            aclr_drv = 0; repeat (4) @(posedge sysclk); #1;
            // Deliberately skip start pulse here.
            for (i = 0; i < 8192; i++)
                send_sample(24'hEE0000 | i[23:0]);
            repeat (CDC_WAIT * 5) @(posedge sysclk); #1;
            if (fft_done === 1'b0)
                $display("PASS [T_START-A] fft_done=0: full frame blocked without start");
            else
                $display("FAIL [T_START-A] fft_done asserted without start being pulsed");

            // Part B: arm the pipeline and send a fresh frame.
            @(posedge sysclk); #1; start = 1;
            @(posedge sysclk); #1; start = 0;
            for (i = 0; i < 8192; i++)
                send_sample(24'hAA0000 | i[23:0]);
            timeout_cnt = 0;
            while (fft_done !== 1'b1 && timeout_cnt < 60000) begin
                @(posedge sysclk); #1;
                timeout_cnt++;
            end
            if (fft_done === 1'b1)
                $display("PASS [T_START-B] fft_done=1 after start pulsed and full frame received");
            else
                $display("FAIL [T_START-B] fft_done never asserted after start (timeout)");
        end

        $display("\n=== All tests complete ===");
        $finish;
    end

    // ── Timeout watchdog ──────────────────────────────────────
    // IVerilog: 5 frames x ~1.8 ms + margin = 30 ms  (T_START adds 2 frames)
    // Questa:   add ~0.35 ms real FFT compute latency = 40 ms
    initial begin
`ifdef QUESTA_FFT
        #40_000_000;
`else
        #30_000_000;
`endif
        $display("TIMEOUT — simulation limit reached");
        $finish;
    end

endmodule
